#!/usr/bin/env bash

forever stop pwnybeads.coffee &> /dev/null
pkill -f "coffee -wco public/js source/coffee"

NODE_ENV=development forever start -a -o pwnybeads.log -e err.log --minUptime 200 --spinSleepTime 1000 -w -c coffee pwnybeads.coffee
coffee -wco public/js source/coffee 2>&1 >> coffee.log &
